package com.example.modmenu.client.ui.screen;

import com.example.modmenu.client.ui.base.BaseResponsiveLodestoneScreen;
import com.example.modmenu.client.ui.base.ScrollableUIContainer;
import com.example.modmenu.client.ui.base.UIElement;
import com.example.modmenu.client.ui.component.ResponsiveButton;
import com.example.modmenu.client.ui.layout.VerticalLayoutContainer;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.FormattedText;

import java.util.ArrayList;
import java.util.List;

public class WikiScreen extends BaseResponsiveLodestoneScreen {
    private final Screen parent;
    private ScrollableUIContainer content;

    public WikiScreen(Screen parent) {
        super(Component.literal("Mod Wiki & Informations"));
        this.parent = parent;
    }

    @Override
    protected void setupLayout() {
        this.layoutRoot.addElement(new ResponsiveButton(10, 10, 50, 20, Component.literal("Back"), btn -> {
            this.minecraft.setScreen(parent);
        }));

        content = new ScrollableUIContainer(50, 40, this.width - 100, this.height - 50);
        this.layoutRoot.addElement(content);

        refreshWiki();
    }

    private void refreshWiki() {
        if (content == null) return;
        content.clearChildren();

        VerticalLayoutContainer list = new VerticalLayoutContainer(0, 0, content.getWidth() - 10, 0, 10);

        addSection(list, "General Overview", "The System Mod is a simulated godhood experience. Through economic domination and system-level overrides, players can transcend standard gameplay limits. Access the main menu via the configured keybind (default: '9'). All interfaces are dynamic and respond in real-time to system changes.");

        addSection(list, "SP Exchange (Meta-Trading)", 
            "§eAccess Control§r: This interface is §lONLY§r accessible once the §6Meta-Trading§r skill is unlocked in the Wealth branch. Access it via the §6Exchange UI§r button on the skill itself.\n\n" +
            "§eCurrency to SP§r: Sacrifice §e$1 Billion§r to gain §d1 SP§r. \n\n" +
            "§eSP to Currency§r: Convert §d1 SP§r into §e$100 Million§r. \n\n" +
            "§7Note: Meta-Trading allows bypassing mob farming for SP if you have a strong economic engine.");

        addSection(list, "Virtual Harvesting (Virtualization)", 
            "A high-performance, lag-free alternative to physical mob grinders. Simulations occur in the background and scale exponentially with your system power.\n\n" +
            "§lStep 1: Enabling Capture Mode§r\n" +
            "Open the §dAbilities§r menu, go to the §dDefense§r section, and toggle §bCapture Mode: ON§r.\n\n" +
            "§lStep 2: Capturing an Entity§r\n" +
            "Find a living entity and §bShift-Right Click§r it. A specialized §dCapture GUI§r will appear.\n\n" +
            "§lStep 3: Choosing Capture Mode§r\n" +
            "- §7Generic§r: Captures basic species. Cost: 10x Max HP in SP.\n" +
            "- §eExact§r: Preserves NBT (Gear, Names, Boss HP). Cost: 100x Max HP in SP.\n\n" +
            "§lStep 4: Management & Expansion§r\n" +
            "You start with §l1 liberated chamber§r. Access the §dVirtual Containment§r menu to purchase up to 10 chambers using SP.\n" +
            "1. §bAssign Weapon§r: Click §bManage§r -> §bSet Weapon§r while holding a tool. Looting/Fire Aspect will apply to all virtual kills.\n" +
            "2. §bSimulation§r: Kills occur every 60s base (reduced by §dSystem Overclock§r and §dClock Speed Injection§r).\n" +
            "3. §bHarvesting§r: Collect XP and Loot directly from the chamber buffer. Use §bReroll Loot§r if you have the required skill.\n\n" +
            "§lAuto-Void & Filtering§r\n" +
            "To prevent the chamber buffer from filling with junk:\n" +
            "1. §bManual Void§r: §bRight-Click§r any item in the Chamber Management screen to void it instantly. The UI updates in real-time.\n" +
            "2. §bAuto-Void Filter§r: Click the §bAuto-Void Filter§r button in a chamber's management screen. Select items to 'Blacklist'. Any blacklisted item generated by the simulation will be automatically discarded before reaching the buffer.\n\n" +
            "§lAdvanced Virtualization Upgrades§r\n" +
            "- §bMulti-Threaded Simulation§r (Max Rank 20): Processes 2^Rank kills per cycle. At Rank 20, you simulate over 1 million kills per cycle.\n" +
            "- §bClock Speed Injection§r (Max Rank 20): Reduces interval drastically. At Rank 20, it hits 1 tick (20 cycles/sec).\n" +
            "- §bIsolated Sandbox§r (Max Rank 1): Bypasses Satiety Registry entirely for 100% efficient farming. Virtual kills never suffer from diminishing returns.\n" +
            "- §bLoot Table Injection§r (Max Rank 20): Guarantees Rare/Epic drops through RNG manipulation. Higher ranks increase Luck significantly.\n" +
            "- §bRecursive Looting§r (Max Rank 20): Simulates virtual Looting X+ enchantments for chambers.\n" +
            "- §bMarket-Linkage§r (Max Rank 1): Auto-liquidation of all drops into cash. Items never enter the buffer; they are sold instantly.\n" +
            "- §bNeural Condensation§r (Max Rank 20): Automatic transmutation of XP into Skill Points. Higher ranks reduce the XP-to-SP exchange rate.\n" +
            "- §bPersistent Simulation§r (Max Rank 1): Processing continues even while you are offline. Catch up on loot upon login.");

        addSection(list, "Item Protection & Locking",
            "Protect your valuable gear using the System's stability protocols.\n\n" +
            "§lHow to use:§r\n" +
            "Hover over an item in any inventory and use §bShift + Right Click§r to cycle through protection modes:\n\n" +
            "1. §cLocked§r (Red Indicator): Prevents the item from being §lsold§r in the Store or §ldropped§r into the world.\n" +
            "2. §bFrozen§r (Blue Indicator): Prevents the item from being §lsold§r, §ldropped§r, or §lmoved§r within your inventory. Perfect for securing your hotbar during combat.\n" +
            "3. §aDisabled§r: Removes all protections.\n\n" +
            "§7Note: Protected items are completely ignored by the 'Sell All' functionality.");

        addSection(list, "Abilities: Mining & Interaction", 
            "§eMining Subroutines§r: \n" +
            "- §bStandard§r: Mines the block you look at and others in range (Configurable).\n" +
            "- §bFocused§r: Mines a linear shaft in your direction of view.\n" +
            "- §bArea§r: Mines a massive cube (up to 65x65x65 with skills).\n" +
            "§7Activation: Use §bShift-Right Click§r with an empty hand. \n\n" +
            "§eAuto-Seller§r: Liquidates items into cash the moment they enter your inventory. Use §dWhitelist§r mode to only sell specific junk, or §dBlacklist§r to protect your gear. Efficiency is affected by §6Market Manipulation§r.\n\n" +
            "§eMagnets§r: Pulls Items and XP. Speed determines how many entities are processed per tick. Range determines the scan radius.\n\n" +
            "§eGrow Crops§r: Passively applies bone-meal effect to all crops in range. Cost per operation applies.");

        addSection(list, "Abilities: Defense & Movement", 
            "§eDamage Cancel§r: Spends money to negate 100% of incoming damage. Cost: $5,000 base + 100x Health per hit. Rank-based discounts apply via §cEfficiency Core§r.\n\n" +
            "§eNo Aggro§r: Broadcasts a 'System-Friend' signal. Most mobs will ignore you entirely. Maintenance fee applies per second.\n\n" +
            "§eFlight§r: Creative-style flight. Costs $500 per second. Efficiency Core can make this free.\n\n" +
            "§eStep Assist§r: Automatically walk up blocks. Height is configurable.\n\n" +
            "§eSure Kill§r: Instantly kills any non-boss mob you look at for a fee. Bosses take massive percentage-based damage instead.");

        addSection(list, "Detailed Skill Tree: Wealth Branch", 
            "§6Market Manipulation§r: +50% sell price per rank. Rank X bypasses dynamic saturation.\n" +
            "§6Compound Interest§r: Passive bank growth (15% @ Rank V). Doubles all rewards.\n" +
            "§6Exponential Bounty§r: Mob rewards scale at (MaxHP^2.5).\n" +
            "§6The Midas Touch§r: Blocks worth 1,000x. Global 10x income multiplier.\n" +
            "§6Investment Portfolio§r: Earn 1 SP per $10B/min.\n" +
            "§6Capitalist Aura§r: 10% Max HP damage/2s to nearby mobs; converted to cash.\n" +
            "§6Wealth Entanglement§r: Passive income based on mineral density of local chunks.\n" +
            "§6Infinite Credit§r: Allows negative balance. Absolute Debt removes all limits.\n" +
            "§6Dividend Protocol§r: Flat massive passive income injection every minute.\n" +
            "§6Currency Singularity§r: Total balance acts as a direct multiplier for all income.\n" +
            "§6Meta-Trading§r: Unlocks SP/Currency exchange UI.\n" +
            "§6Contractual Immortality§r: Auto-respawn on death for a fee.\n" +
            "§6Mercenary Protocol§r: Resurrect killed mobs as scaled allies.\n" +
            "§6Economic Ego§r: Stats scale with the number of 'Zero' digits in your balance.\n" +
            "§6Lobbyist Protocol§r: Reduces SP costs by 5% per rank.\n" +
            "§6Golden Handshake§r: Revival triggers a massive gold explosion.\n" +
            "§6Market Insider§r: 30s warning for Speculation events.\n" +
            "§6Asset Seizure§r: Shift-Right Click to liquidate entity gear.\n" +
            "§6Inflation Control§r: -2% Store buy price per rank.\n" +
            "§6Keystone: Reality Liquidation§r: Earn 25% value of all nearby blocks every second.\n" +
            "§6Keystone: Universal Shareholder§r: $1,000 every 10s per nearby entity.\n" +
            "§6Keystone: Absolute Monopoly§r: $0 Store items + 1% cashback.");

        addSection(list, "Detailed Skill Tree: Combat Branch", 
            "§cEfficiency Core§r: -20% maintenance per rank. Rank V makes it FREE.\n" +
            "§cDefensive Feedback§r: Reflects 20,000% damage. Rank X (Retribution) instantly deletes any entity that dares to strike you.\n" +
            "§cLethal Optimization§r: Sure Kill costs $0 and grants 2x SP.\n" +
            "§cSystem Lockdown§r: Freezes all mobs < 100k HP in 64-block radius.\n" +
            "§cNeural Link§r: Wealth-based Speed/Attack/Reach bonuses. Scale exponentially with your bank balance.\n" +
            "§cAuthority Overload§r: Bonus damage based on a % of your bank balance. Even trillions are supported.\n" +
            "§cCausality Reversal§r: Damage heals you instead of hurting you.\n" +
            "§cEntropy Field§r: -90% Speed/Damage to all mobs in 64 blocks.\n" +
            "§cSoul Reap§r: Permanent attribute gain (HP/Dmg) per kill. God-like stats through persistent harvesting.\n" +
            "§cBlood Data§r: Mob kills have a chance to drop massive SP Data Shards.\n" +
            "§cTemporal Reflex§r: Automatically slows time when in danger.\n" +
            "§cSure Kill Protocol§r: Sure Kill grants up to 500% normal SP.\n" +
            "§cChronos Breach§r: Damage repeats indefinitely every 5s on target.\n" +
            "§cProbability Collapse§r: Forces all random outcomes (Crits, Loot) in your favor.\n" +
            "§cLoot Recalibration§r: Spend SP to reroll mob drops in a custom GUI.\n" +
            "§cSingularity Strike§r: Melee hits create black holes that pull in enemies.\n" +
            "§cTarget Lockdown§r: Tethers mobs within 32 blocks.\n" +
            "§cExecutioner's Tax§r: Every 10th Sure Kill grants a Free Purchase token.\n" +
            "§cOverclocked Reflexes§r: 10% chance per rank to parry projectiles.\n" +
            "§cStatus Override§r: Converts negative effects to positive.\n" +
            "§cCombat Analytics§r: HUD display for mob HP, Loot, and SP value.\n" +
            "§cKeystone: System Sovereignty§r: Invincibility, 10x Flight, Infinite Reach.\n" +
            "§cKeystone: Omnipotence Paradox§r: 100% Max HP Damage + Invincibility.\n" +
            "§cKeystone: Legionary Protocol§r: Summons 3 immortal System Shadows.");

        addSection(list, "Detailed Skill Tree: Utility Branch", 
            "§bQuantum Vacuum§r: Global range, infinite speed item magnet.\n" +
            "§bMolecular Replication§r: Up to 1,000x drops from all mined blocks. Rank X ensures full stacks.\n" +
            "§bBatch Processing§r: Mined items are liquidated instantly, never entering inventory.\n" +
            "§bStructural Refactoring§r: Increases Area Mining to 65x65x65 volume.\n" +
            "§bSpatial Folding§r: Remote menu access (default: 'P') and infinite inventory capacity.\n" +
            "§bBiometric Optimization§r: Permanent Night Vision, Haste V, Flight, and Immunity.\n" +
            "§bMatter Transmutation§r: Rewrite any block (including Bedrock) into another using SP.\n" +
            "§bTotal Chunk Liquidation§r: Delete 5x5 chunk areas for 100% value profit.\n" +
            "§bWormhole Protocol§r: $0 cost teleportation and 'Return to Death' anchor.\n" +
            "§bAtmospheric Control§r: Rewrite world Time, Weather, Gravity, and Tick Speed via Control UI.\n" +
            "§bData Extraction§r: Mobs drop 'System Logs' for massive profit or temporary buffs.\n" +
            "§bSystem Overclock§r: Act at up to 32x normal human speed.\n" +
            "§bMolecular Synthesis§r: Synthesize ANY item from the registry (even modded) using cash via Synthesis UI.\n" +
            "§bVector Manipulation§r: Radiated field that freezes all non-player entities.\n" +
            "§bTectonic Shift§r: Flatten mountains or raise continents with empty-hand clicks.\n" +
            "§bQuantum Storage§r: Shift-Click to sync containers for remote access.\n" +
            "§bMatter Synthesis (Passive)§r: Select item in UI to passively generate stacks.\n" +
            "§bDimensional Anchor (Enhanced)§r: Prevents forced teleports; up to 10 Static Rifts.\n" +
            "§bNBT Refactor§r: Modify item NBT (Names, Attributes) via UI.\n" +
            "§bTime Dilation Aura§r: 16-block field where enemies move at 0.1x speed.\n" +
            "§bKeystone: Architect's Will§r: Look-based appraisal and deletion of ANY block.\n" +
            "§bKeystone: World Root Access§r: /god-style command shell for world rules.\n" +
            "§bKeystone: Eternal Simulation§r: Save/Rollback 128x128 chunk regions.");

        addSection(list, "Detailed Skill Tree: Virtualization Branch", 
            "§dMulti-Threaded Simulation§r: Exponential kill counts per cycle. Up to 1,048,576 kills/cycle at Rank 20.\n" +
            "§dClock Speed Injection§r: Reduces simulation interval drastically. 1 tick (20 cycles/sec) at Rank 20.\n" +
            "§dIsolated Sandbox§r: Bypass Satiety for maximum profit. Rank 1 Max.\n" +
            "§dLoot Table Injection§r: Force Rare/Epic drops through high Luck simulation.\n" +
            "§dRecursive Looting§r: Virtual Looting X+ for chambers. Exceeds standard game limits.\n" +
            "§dMarket-Linkage Protocol§r: Automatic selling of chamber loot. Rank 1 Max.\n" +
            "§dNeural Condensation§r: XP to SP transmutation. Rank 20 reduces exchange rate.\n" +
            "§dPersistent Simulation§r: Offline processing for all chambers. Rank 1 Max.");

        addSection(list, "Executive Protocols (SEP)", 
            "Root-level administrative overrides. Purchased in the §dSystem -> Executive Protocols§r menu.\n\n" +
            "§eInventory Preservation§r: Permanent keepInventory for you ($25,000 SP).\n" +
            "§eChronos Lock§r: Freeze world time and weather permanently ($2,500 SP).\n" +
            "§eGlobal Registry Purge§r: Reset all Mob Satiety instantly ($100,000 SP).\n" +
            "§eGod Strength§r: 10x Multiplier to ALL base damage ($1,000,000 SP).");

        addSection(list, "Store & Economy", 
            "§eDynamic Economy§r: The system tracks every item sold globally. Flooding the market with a single resource (e.g. 10,000 Cobblestone) will exponentially decrease its sell price using the formula P = P0 * 0.95 ^ (volume/1000). \n" +
            "§7Example: Selling items in diverse batches ensures you always get the best rates.\n\n" +
            "§eTrue Cost Algorithm§r: Prices for crafted items are calculated recursively by breaking them down into their most basic raw materials, plus a processing fee. This ensures that modded items with complex recipes are valued fairly.");

        addSection(list, "Administrative Commands", 
            "§e/setcurrentcurrency <player> <amount>§r: Set a player's bank balance.\n" +
            "§e/seteditor <player>§r: Grant editor status to a player, allowing them to modify store prices.\n" +
            "§e/setspmultiplier <multiplier>§r: Scales the amount of SP earned from all sources.\n" +
            "§e/savelayouts§r: Triggers a manual save of the store's UI layout configuration.");

        content.addElement(list);
        content.setContentHeight(list.getHeight() + 20);
    }

    private void addSection(VerticalLayoutContainer list, String title, String text) {
        list.addElement(new WikiSectionElement(0, 0, list.getWidth(), title, text));
    }

    private static class WikiSectionElement extends UIElement {
        private final List<Component> lines = new ArrayList<>();

        public WikiSectionElement(int x, int y, int width, String title, String text) {
            super(x, y, width, 0);
            lines.add(Component.literal("§6§l" + title));
            for (FormattedText s : Minecraft.getInstance().font.getSplitter().splitLines(FormattedText.of(text), width - 10, net.minecraft.network.chat.Style.EMPTY)) {
                lines.add(Component.literal(s.getString()));
            }
            this.height = lines.size() * 10 + 5;
        }

        @Override
        public void render(GuiGraphics g, int mx, int my, float pt) {
            int ty = getY();
            for (Component line : lines) {
                g.drawString(Minecraft.getInstance().font, line, getX() + 5, ty, 0xFFFFFFFF);
                ty += 10;
            }
        }
    }
}
